using System.Collections.Generic;

namespace TelemetryServer.Identifiers.f121
{
    public enum DriverId
    {
        CarlosSainz = 0,
        DaniilKvyat = 1,
        DanielRicciardo = 2,
        FernandoAlonso = 3,
        FelipeMassa = 4,
        KimiRäikkönen = 6,
        LewisHamilton = 7,
        MaxVerstappen = 9,
        NicoHulkenburg = 10, // Corrigido o nome
        KevinMagnussen = 11,
        RomainGrosjean = 12,
        SebastianVettel = 13,
        SergioPerez = 14,
        ValtteriBottas = 15,
        EstebanOcon = 17,
        LanceStroll = 19,
        ArronBarnes = 20,
        MartinGiles = 21,
        AlexMurray = 22,
        LucasRoth = 23,
        IgorCorreia = 24,
        SophieLevasseur = 25,
        JonasSchiffer = 26,
        AlainForest = 27,
        JayLetourneau = 28,
        EstoSaari = 29,
        YasarAtiyeh = 30,
        CallistoCalabresi = 31,
        NaotaIzum = 32,
        HowardClarke = 33,
        WilheimKaufmann = 34,
        MarieLaursen = 35,
        FlavioNieves = 36,
        PeterBelousov = 37,
        KlimekMichalski = 38,
        SantiagoMoreno = 39,
        BenjaminCoppens = 40,
        NoahVisser = 41,
        GertWaldmuller = 42,
        JulianQuesada = 43,
        DanielJones = 44,
        ArtemMarkelov = 45,
        TadasukeMakino = 46,
        SeanGelael = 47,
        NyckDeVries = 48,
        JackAitken = 49,
        GeorgeRussell = 50,
        MaximilianGünther = 51,
        NireiFukuzumi = 52,
        LucaGhiotto = 53,
        LandoNorris = 54,
        SérgioSetteCâmara = 55,
        LouisDelétraz = 56, // Corrigido o nome
        AntonioFuoco = 57,
        CharlesLeclerc = 58,
        PierreGasly = 59,
        AlexanderAlbon = 62,
        NicholasLatifi = 63,
        DorianBoccolacci = 64,
        NikoKari = 65,
        RobertoMerhi = 66,
        ArjunMaini = 67,
        AlessioLorandi = 68,
        RubenMeijer = 69,
        RashidNair = 70,
        JackTremblay = 71,
        DevonButler = 72,
        LukasWeber = 73,
        AntonioGiovinazzi = 74,
        RobertKubica = 75,
        AlainProst = 76,
        AyrtonSenna = 77,
        NobuharuMatsushita = 78,
        NikitaMazepin = 79,
        GuanyuZhou = 80,
        MickSchumacher = 81,
        CallumIlott = 82,
        JuanManuelCorrea = 83,
        JordanKing = 84,
        MahaveerRaghunathan = 85,
        TatianaCalderon = 86,
        AnthoineHubert = 87,
        GiulianoAlesi = 88,
        RalphBoschung = 89,
        MichaelSchumacher = 90,
        DanTicktum = 91,
        MarcusArmstrong = 92,
        ChristianLundgaard = 93,
        YukiTsunoda = 94,
        JehanDaruvala = 95,
        GuilhermeSamaia = 96,
        PedroPiquet = 97,
        FelipeDrugovich = 98,
        RobertShwartzman = 99,
        RoyNissany = 100,
        MarinoSato = 101,
        AidanJackson = 102,
        CasperAkkerman = 103,
        JensonButton = 109,
        DavidCoulthard = 110,
        NicoRosberg = 111
    }

    public static class DriverIdentifier
    {
        private static readonly Dictionary<DriverId, string> DriverNames = new Dictionary<DriverId, string>()
        {
            { DriverId.CarlosSainz, "Carlos Sainz" },
            { DriverId.DaniilKvyat, "Daniil Kvyat" },
            { DriverId.DanielRicciardo, "Daniel Ricciardo" },
            { DriverId.FernandoAlonso, "Fernando Alonso" },
            { DriverId.FelipeMassa, "Felipe Massa" },
            { DriverId.KimiRäikkönen, "Kimi Räikkönen" },
            { DriverId.LewisHamilton, "Lewis Hamilton" },
            { DriverId.MaxVerstappen, "Max Verstappen" },
            { DriverId.NicoHulkenburg, "Nico Hulkenburg" },
            { DriverId.KevinMagnussen, "Kevin Magnussen" },
            { DriverId.RomainGrosjean, "Romain Grosjean" },
            { DriverId.SebastianVettel, "Sebastian Vettel" },
            { DriverId.SergioPerez, "Sergio Perez" },
            { DriverId.ValtteriBottas, "Valtteri Bottas" },
            { DriverId.EstebanOcon, "Esteban Ocon" },
            { DriverId.LanceStroll, "Lance Stroll" },
            { DriverId.ArronBarnes, "Arron Barnes" },
            { DriverId.MartinGiles, "Martin Giles" },
            { DriverId.AlexMurray, "Alex Murray" },
            { DriverId.LucasRoth, "Lucas Roth" },
            { DriverId.IgorCorreia, "Igor Correia" },
            { DriverId.SophieLevasseur, "Sophie Levasseur" },
            { DriverId.JonasSchiffer, "Jonas Schiffer" },
            { DriverId.AlainForest, "Alain Forest" },
            { DriverId.JayLetourneau, "Jay Letourneau" },
            { DriverId.EstoSaari, "Esto Saari" },
            { DriverId.YasarAtiyeh, "Yasar Atiyeh" },
            { DriverId.CallistoCalabresi, "Callisto Calabresi" },
            { DriverId.NaotaIzum, "Naota Izum" },
            { DriverId.HowardClarke, "Howard Clarke" },
            { DriverId.WilheimKaufmann, "Wilheim Kaufmann" },
            { DriverId.MarieLaursen, "Marie Laursen" },
            { DriverId.FlavioNieves, "Flavio Nieves" },
            { DriverId.PeterBelousov, "Peter Belousov" },
            { DriverId.KlimekMichalski, "Klimek Michalski" },
            { DriverId.SantiagoMoreno, "Santiago Moreno" },
            { DriverId.BenjaminCoppens, "Benjamin Coppens" },
            { DriverId.NoahVisser, "Noah Visser" },
            { DriverId.GertWaldmuller, "Gert Waldmuller" },
            { DriverId.JulianQuesada, "Julian Quesada" },
            { DriverId.DanielJones, "Daniel Jones" },
            { DriverId.ArtemMarkelov, "Artem Markelov" },
            { DriverId.TadasukeMakino, "Tadasuke Makino" },
            { DriverId.SeanGelael, "Sean Gelael" },
            { DriverId.NyckDeVries, "Nyck De Vries" },
            { DriverId.JackAitken, "Jack Aitken" },
            { DriverId.GeorgeRussell, "George Russell" },
            { DriverId.MaximilianGünther, "Maximilian Günther" },
            { DriverId.NireiFukuzumi, "Nirei Fukuzumi" },
            { DriverId.LucaGhiotto, "Luca Ghiotto" },
            { DriverId.LandoNorris, "Lando Norris" },
            { DriverId.SérgioSetteCâmara, "Sérgio Sette Câmara" },
            { DriverId.LouisDelétraz, "Louis Delétraz" },
            { DriverId.AntonioFuoco, "Antonio Fuoco" },
            { DriverId.CharlesLeclerc, "Charles Leclerc" },
            { DriverId.PierreGasly, "Pierre Gasly" },
            { DriverId.AlexanderAlbon, "Alexander Albon" },
            { DriverId.NicholasLatifi, "Nicholas Latifi" },
            { DriverId.DorianBoccolacci, "Dorian Boccolacci" },
            { DriverId.NikoKari, "Niko Kari" },
            { DriverId.RobertoMerhi, "Roberto Merhi" },
            { DriverId.ArjunMaini, "Arjun Maini" },
            { DriverId.AlessioLorandi, "Alessio Lorandi" },
            { DriverId.RubenMeijer, "Ruben Meijer" },
            { DriverId.RashidNair, "Rashid Nair" },
            { DriverId.JackTremblay, "Jack Tremblay" },
            { DriverId.DevonButler, "Devon Butler" },
            { DriverId.LukasWeber, "Lukas Weber" },
            { DriverId.AntonioGiovinazzi, "Antonio Giovinazzi" },
            { DriverId.RobertKubica, "Robert Kubica" },
            { DriverId.AlainProst, "Alain Prost" },
            { DriverId.AyrtonSenna, "Ayrton Senna" },
            { DriverId.NobuharuMatsushita, "Nobuharu Matsushita" },
            { DriverId.NikitaMazepin, "Nikita Mazepin" },
            { DriverId.GuanyuZhou, "Guanyu Zhou" },
            { DriverId.MickSchumacher, "Mick Schumacher" },
            { DriverId.CallumIlott, "Callum Ilott" },
            { DriverId.JuanManuelCorrea, "Juan Manuel Correa" },
            { DriverId.JordanKing, "Jordan King" },
            { DriverId.MahaveerRaghunathan, "Mahaveer Raghunathan" },
            { DriverId.TatianaCalderon, "Tatiana Calderon" },
            { DriverId.AnthoineHubert, "Anthoine Hubert" },
            { DriverId.GiulianoAlesi, "Giuliano Alesi" },
            { DriverId.RalphBoschung, "Ralph Boschung" },
            { DriverId.MichaelSchumacher, "Michael Schumacher" },
            { DriverId.DanTicktum, "Dan Ticktum" },
            { DriverId.MarcusArmstrong, "Marcus Armstrong" },
            { DriverId.ChristianLundgaard, "Christian Lundgaard" },
            { DriverId.YukiTsunoda, "Yuki Tsunoda" },
            { DriverId.JehanDaruvala, "Jehan Daruvala" },
            { DriverId.GuilhermeSamaia, "Guilherme Samaia" },
            { DriverId.PedroPiquet, "Pedro Piquet" },
            { DriverId.FelipeDrugovich, "Felipe Drugovich" },
            { DriverId.RobertShwartzman, "Robert Shwartzman" },
            { DriverId.RoyNissany, "Roy Nissany" },
            { DriverId.MarinoSato, "Marino Sato" },
            { DriverId.AidanJackson, "Aidan Jackson" },
            { DriverId.CasperAkkerman, "Casper Akkerman" },
            { DriverId.JensonButton, "Jenson Button" },
            { DriverId.DavidCoulthard, "David Coulthard" },
            { DriverId.NicoRosberg, "Nico Rosberg" }
        };

        public static string GetDriverName(byte driverId)
        {
            if (DriverNames.TryGetValue((DriverId)driverId, out string driverName))
            {
                return driverName;
            }
            return "Piloto Desconhecido";
        }
    }
}
