using System.Collections.Generic;

namespace TelemetryServer.Identifiers.f120
{
    public enum DriverId
    {
        CarlosSainz = 0,
        DaniilKvyat = 1,
        DanielRicciardo = 2,
        KimiRäikkönen = 6,
        LewisHamilton = 7,
        MaxVerstappen = 9,
        NicoHulkenberg = 10,
        KevinMagnussen = 11,
        RomainGrosjean = 12,
        SebastianVettel = 13,
        SergioPerez = 14,
        ValtteriBottas = 15,
        EstebanOcon = 17,
        LanceStroll = 19,
        ArronBarnes = 20,
        MartinGiles = 21,
        AlexMurray = 22,
        LucasRoth = 23,
        IgorCorreia = 24,
        SophieLevasseur = 25,
        JonasSchiffer = 26,
        AlainForest = 27,
        JayLetourneau = 28,
        EstoSaari = 29,
        YasarAtiyeh = 30,
        CallistoCalabresi = 31,
        NaotaIzum = 32,
        HowardClarke = 33,
        WilhelmKaufmann = 34,
        MarieLaursen = 35,
        FlavioNieves = 36,
        PeterBelousov = 37,
        KlimekMichalski = 38,
        SantiagoMoreno = 39,
        BenjaminCoppens = 40,
        NoahVisser = 41,
        GertWaldmuller = 42,
        JulianQuesada = 43,
        DanielJones = 44,
        ArtemMarkelov = 45,
        TadasukeMakino = 46,
        SeanGelael = 47,
        NyckDeVries = 48,
        JackAitken = 49,
        GeorgeRussell = 50,
        MaximilianGünther = 51,
        NireiFukuzumi = 52,
        LucaGhiotto = 53,
        LandoNorris = 54,
        SergioSetteCâmara = 55,
        LouisDeletraz = 56,
        AntonioFuoco = 57,
        CharlesLeclerc = 58,
        PierreGasly = 59,
        AlexanderAlbon = 62,
        NicholasLatifi = 63,
        DorianBoccolacci = 64,
        NikoKari = 65,
        RobertoMerhi = 66,
        ArjunMaini = 67,
        AlessioLorandi = 68,
        RubenMeijer = 69,
        RashidNair = 70,
        JackTremblay = 71,
        AntonioGiovinazzi = 74,
        RobertKubica = 75,
        NobuharuMatsushita = 78,
        NikitaMazepin = 79,
        GuanyuZhou = 80,
        MickSchumacher = 81,
        CallumIlott = 82,
        JuanManuelCorrea = 83,
        JordanKing = 84,
        MahaveerRaghunathan = 85,
        TatianaCalderon = 86,
        AnthoineHubert = 87,
        GiulianoAlesi = 88,
        RalphBoschung = 89
    }

    public static class DriverIdentifier
    {
        private static readonly Dictionary<DriverId, string> DriverNames = new Dictionary<DriverId, string>()
        {
            { DriverId.CarlosSainz, "Carlos Sainz" },
            { DriverId.DaniilKvyat, "Daniil Kvyat" },
            { DriverId.DanielRicciardo, "Daniel Ricciardo" },
            { DriverId.KimiRäikkönen, "Kimi Räikkönen" },
            { DriverId.LewisHamilton, "Lewis Hamilton" },
            { DriverId.MaxVerstappen, "Max Verstappen" },
            { DriverId.NicoHulkenberg, "Nico Hulkenberg" },
            { DriverId.KevinMagnussen, "Kevin Magnussen" },
            { DriverId.RomainGrosjean, "Romain Grosjean" },
            { DriverId.SebastianVettel, "Sebastian Vettel" },
            { DriverId.SergioPerez, "Sergio Perez" },
            { DriverId.ValtteriBottas, "Valtteri Bottas" },
            { DriverId.EstebanOcon, "Esteban Ocon" },
            { DriverId.LanceStroll, "Lance Stroll" },
            { DriverId.ArronBarnes, "Arron Barnes" },
            { DriverId.MartinGiles, "Martin Giles" },
            { DriverId.AlexMurray, "Alex Murray" },
            { DriverId.LucasRoth, "Lucas Roth" },
            { DriverId.IgorCorreia, "Igor Correia" },
            { DriverId.SophieLevasseur, "Sophie Levasseur" },
            { DriverId.JonasSchiffer, "Jonas Schiffer" },
            { DriverId.AlainForest, "Alain Forest" },
            { DriverId.JayLetourneau, "Jay Letourneau" },
            { DriverId.EstoSaari, "Esto Saari" },
            { DriverId.YasarAtiyeh, "Yasar Atiyeh" },
            { DriverId.CallistoCalabresi, "Callisto Calabresi" },
            { DriverId.NaotaIzum, "Naota Izum" },
            { DriverId.HowardClarke, "Howard Clarke" },
            { DriverId.WilhelmKaufmann, "Wilhelm Kaufmann" },
            { DriverId.MarieLaursen, "Marie Laursen" },
            { DriverId.FlavioNieves, "Flavio Nieves" },
            { DriverId.PeterBelousov, "Peter Belousov" },
            { DriverId.KlimekMichalski, "Klimek Michalski" },
            { DriverId.SantiagoMoreno, "Santiago Moreno" },
            { DriverId.BenjaminCoppens, "Benjamin Coppens" },
            { DriverId.NoahVisser, "Noah Visser" },
            { DriverId.GertWaldmuller, "Gert Waldmuller" },
            { DriverId.JulianQuesada, "Julian Quesada" },
            { DriverId.DanielJones, "Daniel Jones" },
            { DriverId.ArtemMarkelov, "Artem Markelov" },
            { DriverId.TadasukeMakino, "Tadasuke Makino" },
            { DriverId.SeanGelael, "Sean Gelael" },
            { DriverId.NyckDeVries, "Nyck De Vries" },
            { DriverId.JackAitken, "Jack Aitken" },
            { DriverId.GeorgeRussell, "George Russell" },
            { DriverId.MaximilianGünther, "Maximilian Günther" },
            { DriverId.NireiFukuzumi, "Nirei Fukuzumi" },
            { DriverId.LucaGhiotto, "Luca Ghiotto" },
            { DriverId.LandoNorris, "Lando Norris" },
            { DriverId.SergioSetteCâmara, "Sérgio Sette Câmara" },
            { DriverId.LouisDeletraz, "Louis Delétraz" },
            { DriverId.AntonioFuoco, "Antonio Fuoco" },
            { DriverId.CharlesLeclerc, "Charles Leclerc" },
            { DriverId.PierreGasly, "Pierre Gasly" },
            { DriverId.AlexanderAlbon, "Alexander Albon" },
            { DriverId.NicholasLatifi, "Nicholas Latifi" },
            { DriverId.DorianBoccolacci, "Dorian Boccolacci" },
            { DriverId.NikoKari, "Niko Kari" },
            { DriverId.RobertoMerhi, "Roberto Merhi" },
            { DriverId.ArjunMaini, "Arjun Maini" },
            { DriverId.AlessioLorandi, "Alessio Lorandi" },
            { DriverId.RubenMeijer, "Ruben Meijer" },
            { DriverId.RashidNair, "Rashid Nair" },
            { DriverId.JackTremblay, "Jack Tremblay" },
            { DriverId.AntonioGiovinazzi, "Antonio Giovinazzi" },
            { DriverId.RobertKubica, "Robert Kubica" },
            { DriverId.NobuharuMatsushita, "Nobuharu Matsushita" },
            { DriverId.NikitaMazepin, "Nikita Mazepin" },
            { DriverId.GuanyuZhou, "Guanyu Zhou" },
            { DriverId.MickSchumacher, "Mick Schumacher" },
            { DriverId.CallumIlott, "Callum Ilott" },
            { DriverId.JuanManuelCorrea, "Juan Manuel Correa" },
            { DriverId.JordanKing, "Jordan King" },
            { DriverId.MahaveerRaghunathan, "Mahaveer Raghunathan" },
            { DriverId.TatianaCalderon, "Tatiana Calderón" },
            { DriverId.AnthoineHubert, "Anthoine Hubert" },
            { DriverId.GiulianoAlesi, "Giuliano Alesi" },
            { DriverId.RalphBoschung, "Ralph Boschung" }
        };

        public static string GetDriverName(byte driverId)
        {
            if (DriverNames.TryGetValue((DriverId)driverId, out string driverName))
            {
                return driverName;
            }
            return "Piloto Desconhecido";
        }
    }
}
