using System.Collections.Generic;

namespace TelemetryServer.Identifiers.f122
{
    public enum NationalityId
    {
        American = 1,
        Argentinian = 2,
        Australian = 3,
        Austrian = 4,
        Azerbaijani = 5,
        Bahraini = 6,
        Belgian = 7,
        Bolivian = 8,
        Brazilian = 9,
        British = 10,
        Bulgarian = 11,
        Cameroonian = 12,
        Canadian = 13,
        Chilean = 14,
        Chinese = 15,
        Colombian = 16,
        CostaRican = 17,
        Croatian = 18,
        Cypriot = 19,
        Czech = 20,
        Danish = 21,
        Dutch = 22,
        Ecuadorian = 23,
        English = 24,
        Emirian = 25,
        Estonian = 26,
        Finnish = 27,
        French = 28,
        German = 29,
        Ghanaian = 30,
        Greek = 31,
        Guatemalan = 32,
        Honduran = 33,
        HongKonger = 34,
        Hungarian = 35,
        Icelander = 36,
        Indian = 37,
        Indonesian = 38,
        Irish = 39,
        Israeli = 40,
        Italian = 41,
        Jamaican = 42,
        Japanese = 43,
        Jordanian = 44,
        Kuwaiti = 45,
        Latvian = 46,
        Lebanese = 47,
        Lithuanian = 48,
        Luxembourger = 49,
        Malaysian = 50,
        Maltese = 51,
        Mexican = 52,
        Monegasque = 53,
        NewZealander = 54,
        Nicaraguan = 55,
        NorthernIrish = 56, // Corrigido com base na lista
        Norwegian = 57, // Corrigido com base na lista
        Omani = 58,
        Pakistani = 59,
        Panamanian = 60,
        Paraguayan = 61,
        Peruvian = 62,
        Polish = 63,
        Portuguese = 64,
        Qatari = 65,
        Romanian = 66,
        Russian = 67,
        Salvadoran = 68,
        Saudi = 69,
        Scottish = 70,
        Serbian = 71,
        Singaporean = 72,
        Slovakian = 73,
        Slovenian = 74,
        SouthKorean = 75,
        SouthAfrican = 76,
        Spanish = 77,
        Swedish = 78,
        Swiss = 79,
        Thai = 80,
        Turkish = 81,
        Uruguayan = 82,
        Ukrainian = 83,
        Venezuelan = 84,
        Barbadian = 85,
        Welsh = 86,
        Vietnamese = 87,
        Unknown = 255
    }

    public static class NationalityIdentifier
    {
        private static readonly Dictionary<NationalityId, string> NationalityNames = new Dictionary<NationalityId, string>()
        {
            { NationalityId.American, "American" },
            { NationalityId.Argentinian, "Argentinian" },
            { NationalityId.Australian, "Australian" },
            { NationalityId.Austrian, "Austrian" },
            { NationalityId.Azerbaijani, "Azerbaijani" },
            { NationalityId.Bahraini, "Bahraini" },
            { NationalityId.Belgian, "Belgian" },
            { NationalityId.Bolivian, "Bolivian" },
            { NationalityId.Brazilian, "Brazilian" },
            { NationalityId.British, "British" },
            { NationalityId.Bulgarian, "Bulgarian" },
            { NationalityId.Cameroonian, "Cameroonian" },
            { NationalityId.Canadian, "Canadian" },
            { NationalityId.Chilean, "Chilean" },
            { NationalityId.Chinese, "Chinese" },
            { NationalityId.Colombian, "Colombian" },
            { NationalityId.CostaRican, "Costa Rican" },
            { NationalityId.Croatian, "Croatian" },
            { NationalityId.Cypriot, "Cypriot" },
            { NationalityId.Czech, "Czech" },
            { NationalityId.Danish, "Danish" },
            { NationalityId.Dutch, "Dutch" },
            { NationalityId.Ecuadorian, "Ecuadorian" },
            { NationalityId.English, "English" },
            { NationalityId.Emirian, "Emirian" },
            { NationalityId.Estonian, "Estonian" },
            { NationalityId.Finnish, "Finnish" },
            { NationalityId.French, "French" },
            { NationalityId.German, "German" },
            { NationalityId.Ghanaian, "Ghanaian" },
            { NationalityId.Greek, "Greek" },
            { NationalityId.Guatemalan, "Guatemalan" },
            { NationalityId.Honduran, "Honduran" },
            { NationalityId.HongKonger, "Hong Konger" },
            { NationalityId.Hungarian, "Hungarian" },
            { NationalityId.Icelander, "Icelander" },
            { NationalityId.Indian, "Indian" },
            { NationalityId.Indonesian, "Indonesian" },
            { NationalityId.Irish, "Irish" },
            { NationalityId.Israeli, "Israeli" },
            { NationalityId.Italian, "Italian" },
            { NationalityId.Jamaican, "Jamaican" },
            { NationalityId.Japanese, "Japanese" },
            { NationalityId.Jordanian, "Jordanian" },
            { NationalityId.Kuwaiti, "Kuwaiti" },
            { NationalityId.Latvian, "Latvian" },
            { NationalityId.Lebanese, "Lebanese" },
            { NationalityId.Lithuanian, "Lithuanian" },
            { NationalityId.Luxembourger, "Luxembourger" },
            { NationalityId.Malaysian, "Malaysian" },
            { NationalityId.Maltese, "Maltese" },
            { NationalityId.Mexican, "Mexican" },
            { NationalityId.Monegasque, "Monegasque" },
            { NationalityId.NewZealander, "New Zealander" },
            { NationalityId.Nicaraguan, "Nicaraguan" },
            { NationalityId.NorthernIrish, "Northern Irish" },
            { NationalityId.Norwegian, "Norwegian" },
            { NationalityId.Omani, "Omani" },
            { NationalityId.Pakistani, "Pakistani" },
            { NationalityId.Panamanian, "Panamanian" },
            { NationalityId.Paraguayan, "Paraguayan" },
            { NationalityId.Peruvian, "Peruvian" },
            { NationalityId.Polish, "Polish" },
            { NationalityId.Portuguese, "Portuguese" },
            { NationalityId.Qatari, "Qatari" },
            { NationalityId.Romanian, "Romanian" },
            { NationalityId.Russian, "Russian" },
            { NationalityId.Salvadoran, "Salvadoran" },
            { NationalityId.Saudi, "Saudi" },
            { NationalityId.Scottish, "Scottish" },
            { NationalityId.Serbian, "Serbian" },
            { NationalityId.Singaporean, "Singaporean" },
            { NationalityId.Slovakian, "Slovakian" },
            { NationalityId.Slovenian, "Slovenian" },
            { NationalityId.SouthKorean, "South Korean" },
            { NationalityId.SouthAfrican, "South African" },
            { NationalityId.Spanish, "Spanish" },
            { NationalityId.Swedish, "Swedish" },
            { NationalityId.Swiss, "Swiss" },
            { NationalityId.Thai, "Thai" },
            { NationalityId.Turkish, "Turkish" },
            { NationalityId.Uruguayan, "Uruguayan" },
            { NationalityId.Ukrainian, "Ukrainian" },
            { NationalityId.Venezuelan, "Venezuelan" },
            { NationalityId.Barbadian, "Barbadian" },
            { NationalityId.Welsh, "Welsh" },
            { NationalityId.Vietnamese, "Vietnamese" }
        };

        public static string GetNationalityName(byte nationalityId)
        {
            if (NationalityNames.TryGetValue((NationalityId)nationalityId, out string nationalityName))
            {
                return nationalityName;
            }
            return "Nacionalidade Desconhecida";
        }
    }
}
